// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace SpeachAnalyzerML.Model
{
    public class ModelInput
    {
        [ColumnName("Content"), LoadColumn(0)]
        public string Content { get; set; }


        [ColumnName("Party"), LoadColumn(1)]
        public string Party { get; set; }


    }
}
